---
title: "Ipomopsis nitrogen experiment 1 volatiles"
author: "Janelle Bohey, John Powers"
date: "`r Sys.Date()`"
output: 
  html_document:
    self_contained: no
    lib_dir: libs
    code_folding: hide
    toc: yes
    toc_float: TRUE 
editor_options: 
  chunk_output_type: console
---
<style type="text/css">
.main-container { max-width: 1000px; margin-left: 0; margin-right: auto; }
img{ max-width:200%; height: auto; }
td, th { padding : 6px }
</style>

```{r setup, include=FALSE}
library(reshape2)
library(tidyverse)
library(lubridate)
library(vegan)
library(knitr)
#install.packages("remotes")
#remotes::install_github("jmpowers/bouquet", build_vignettes = TRUE)
library(bouquet)
knitr::opts_chunk$set(comment="", cache=T, warning=F, message=F, 
                      fig.path = "plots-nitrogen/", dev="svglite", dev.args=list(fix_text_size=FALSE), fig.height=8, fig.width=10)
```

```{r read_scents}
# library(googlesheets4)
# exp1_meta <- read_sheet("1k2XJUsRyTsQEeEoZE24yTvsl7kSyf2Gg6gehs8pUvOo", sheet="metadata", guess_max=200) %>% 
#   mutate(plant = as.character(plant))
# exp2_meta <- read_sheet("1EwPMsBAxqrRtuqH4uUBtthUOZlQluQICSvNr9u87h0E", sheet="metadata", guess_max=200) %>% 
#   mutate(plant = as.character(plant))
# gc_verdicts <- read_sheet("1X8oo7qZlo1p6MVl_CBeBe6CUTHEAcd-FWQzfHud3Qws", sheet = "2022gc220929") %>% 
#   mutate(sample2 = ifelse(is.na(sample), FileName, sample))
# exp1_verdicts <- gc_verdicts %>% filter(sample2 %in% exp1_meta$filename)
# exp2leaf_verdicts <- gc_verdicts %>% filter(sample2 %in% exp2_meta$filename)
# write_csv(exp1_verdicts, file = "data/exp1_verdicts.csv")
# write_csv(exp2leaf_verdicts, file = "data/exp2leaf_verdicts.csv")
# load("~/MyDocs/MEGA/UCI/Schiedea/Analysis/scent/rmbl/Inventory/shimadzu_data_22.rda")
# exp1.data <- shimadzu.data.22 %>% filter(Filename %in% exp1_verdicts$FileName)
# exp2leaf.data <- shimadzu.data.22 %>% filter(Filename %in% exp2_verdicts$FileName)
# save(exp1.data, file = "data/exp1_data.rda")
# save(exp2leaf.data, file = "data/exp2leaf_data.rda")

exp1.verdicts <- read_csv("data/exp1_verdicts.csv")
load("data/exp1_data.rda") #loads exp1.data (Shimadzu output)
exp1.data <- exp1.data %>% left_join(select(exp1.verdicts, Filename = FileName, sample2)) %>% 
  select(-Filename) %>% rename(Filename = sample2) %>%  #replace FileName with the sample2 it holds (accounts for skips)
  droplevels()

# load short names
ipochems <- read_csv("data/Ipo volatile compounds - chemsf_ipo.csv") %>% 
  select(name, shortname, standard, verdict) %>%  filter(verdict != "")
            
#shorten chemical names and merge compounds with multiple names
shortnames <- ipochems %>% select(name, shortname) %>% filter(shortname!="") %>% deframe()

exp1.data$Name <- recode(exp1.data$Name, !!!shortnames)

exp1.all <- dcast(exp1.data, Filename~Name, sum, value.var="Area")
rownames(exp1.all) <- exp1.all[,1]
exp1.all[,1] <- NULL
```

# Read metadata

```{r metadata, fig.height=5, fig.width=5}
metadata <- read_csv("data/EXP 1 (N) Volatile sampling  - metadata.csv") %>% 
  filter(filename != "#N/A") %>% 
  mutate(plantid = paste(species, plant), speciestime = paste(species, time, sep=".")) %>% 
  left_join(read_csv("data/exp1_treatments.csv") %>% mutate(plant = as.character(plant)))
rownames(metadata) <- metadata$filename
metadata <- metadata[rownames(exp1.all),] #order metaddata to match order of data

metadata %>% count(species, time, treatment) %>% kable()
metadata %>% filter(species !="AMB") %>% count(species, plantid, time) %>% 
  ggplot(aes(x=n, fill=time))+ geom_histogram(binwidth=1) + facet_wrap(vars(time), ncol=1)+
  labs(x="Samples per plant") 

metadata %>% filter(species !="AMB") %>% group_by(time) %>% 
  mutate(pump.dt = ymd_hms(paste(date, pump)), pump.hr = hour(pump.dt)+minute(pump.dt)/60,
         bag.dt = ymd_hms(paste(date, bag)), bag.hr = hour(bag.dt)+minute(bag.dt)/60,
         end.dt = ymd_hms(paste(date, bag)), end.hr = hour(end.dt)+minute(end.dt)/60) %>% 
  summarize(min=min(bag.hr), max=max(end.hr))  %>% kable(caption="first bag time, last ending time, in hr", digits=2)

ggplot(metadata, aes(y=equil, x=species)) + geom_boxplot() + labs(y="Equilibration duration")
ggplot(metadata, aes(y=pumping, x=species)) + geom_boxplot() + labs(y="Pumping duration")

metadata %>% count(species) %>% kable(caption="total volatile samples by species")

digging_date <- ymd("2022-06-24")
treatment_date <- digging_date + days(6)
ggplot(metadata, aes(x=date-treatment_date, fill=species))+geom_histogram(binwidth=1)
metadata %>% count(date-treatment_date) %>% kable(caption=paste("days since treatments began on", treatment_date))
```

# Filtering

```{r filtering}
metadata <- metadata %>% mutate(type= ifelse(species=="AMB", "ambient","floral")) %>% rename(trap=sample) %>% as.data.frame() %>% 
  load_metadata(date = "date", sample = "filename", group = "speciestime", type = "type") #combine species and time (previously separate)

longdata <- load_longdata(exp1.data, sample = "Filename", RT = "Ret.Time", 
                          name = "Name", area = "Area", match = "SI", maxmatch=100)

sampletable <- make_sampletable(longdata, metadata)

chemtable <- make_chemtable(longdata, metadata) %>% 
  filter_RT(2, 17) %>% 
  filter_match(0.8) %>% 
  filter_freq(0.2, group = TRUE) %>% 
  filter_contaminant(cont.list = c("13-Methyltetradecanal","Cyclohexane, 1,1-dimethyl-2-propyl-","2-hexyldecan-1-ol","Tridecane, 3-methylene-")) %>% 
  filter_area(min_maximum = 1e5) %>%
  filter_ambient_ratio(sampletable, metadata, ratio = 3) %>% 
  filter_ambient_ttest(sampletable, metadata, 
                       alpha = 0.05, adjust = "fdr") 
chemtable$filter_final <- with(chemtable, filter_RT == "OK" & filter_match =="OK" & 
                                 #(filter_freq.agg == "OK" | filter_freq.ten == "OK" | filter_freq.D == "OK" | filter_freq.N == "OK") &
                                 (filter_freq.agg.N == "OK" | filter_freq.ten.N == "OK" | filter_freq.agg.D == "OK" | filter_freq.ten.D == "OK") &
                                 filter_area == "OK" & filter_ambient_ratio == "OK" & filter_ambient_ttest == "OK" & filter_contaminant == "OK")

plot_filters(chemtable, option="rarity")
plot_filters(chemtable, option="ambient")
plot_filters(chemtable, option="volcano")
plot_filters(chemtable, option="prop")

vol.qual <- prune_sampletable(sampletable, chemtable, metadata)
files_exclude <- c("NEXP1_agg6n3_N_220725_8152022_10.qgd") # flower fell off
vol.qual <- vol.qual[!(rownames(vol.qual) %in% files_exclude) ,]
meta <- metadata[metadata$type == "floral" & !(metadata$sample %in% files_exclude),] %>% droplevels()
vol.qual <- vol.qual / (as.numeric(meta$equil + meta$pumping)/3600) / meta$flrs #0.5 hr of equilibration plus 0.25 hr pumping, one flower
```

# Quantitative integrations

```{r quant}
#read in the large 2022 quant integration output and cut it down to NEXP chromatograms
# source("read_shimadzu.R")
# quantpath <- "~/MyDocs/MEGA/UCI/Schiedea/Analysis/scent/rmbl/RMBL Batches/quant_round3/"
# bfiles <-  list.files(quantpath)
# quant.full <- map_dfr(set_names(paste0(quantpath, bfiles), bfiles), read.shimadzu.quant, .id="batch") %>% 
#   mutate(Name = trimws(Name), Area=replace_na(Area, 0)) %>% 
#   distinct(Filename, Name, .keep_all=T)
# quant.full %>% select(batch, Dirname, Filename, Name, Area) %>% 
#   mutate(Dirname = fct_relabel(Dirname, str_remove, "C:/GCMSsolution/Data/Project1_190815/")) %>% 
#   filter(Name != "1,6,10-Dodecatrien-3-ol, 3,7,11-trimethyl-") %>% 
#   mutate(Name = recode(Name, !!!shortnames)) %>% 
#   filter(str_detect(Filename, "^NEXP")) %>% select(-Dirname, -batch) %>%
#   pivot_wider(names_from="Name", values_from="Area") %>%
#   write_tsv("data/quant_2022.tsv")

vol <- read_tsv("data/quant_2022.tsv") %>%  
  left_join(select(exp1.verdicts, Filename = FileName, sample2)) %>% drop_na(sample2) %>% 
  select(-Filename) %>% rename(Filename = sample2) %>%  #replace FileName with the sample2 it holds (accounts for skips)
  column_to_rownames("Filename")
contams <- c("methyl salicylate", "benzaldehyde","trans-Geranylgeraniol","Decanal", "D-limonene", "Nonanoic acid", "caprolactam",
             "3-methylbutanal oxime")#passed bouquet in OTC experiment but rare here
vol <- vol[rownames(vol.qual), !colnames(vol) %in% contams]
vol <- vol / (as.numeric(meta$equil + meta$pumping)/3600) / meta$flrs #0.5 hr of equilibration plus 0.25 hr pumping, one flower

(added_quant <- setdiff(colnames(vol), colnames(vol.qual)))#in quant (from temp experiment) but do not pass filters in this dataset
(new_quant <- colnames(vol)[28:34]) #newly integrated, pass filters
(need_quant <- setdiff(colnames(vol.qual), colnames(vol))) # filtered volatiles that need quant integration. 
vol <- bind_cols(vol, vol.qual[,need_quant]) #temporary, add a couple volatiles that don't have quant integrations yet (currently not on same scale!)
```

```{r diverse, eval=FALSE}
#optional - look for a set of chromatograms that have all of the volatiles needed to set up Shimadzu quantitative integrations
best <- list()
i <- 1
vol.left <- vol.qual[,need_quant]^(1/4) # halfway between areas and presence-absence
while(ncol(vol.left)>0) {
  print(dim(vol.left))
  best[[i]] <- which.max(rowSums(vol.left))
  vol.left <- vol.left[ , !decostand(vol.left[best[[i]],], method="pa"), drop=FALSE]
  i <- i+1
}
(best.vol <- as.data.frame(t(vol.qual[unlist(best),need_quant])) %>% rownames_to_column("name"))
chemtable %>% filter(name %in% need_quant) %>% select(name, RT, RT.var) %>% arrange(RT)
```

# Retention times

```{r retention, fig.width=12}
longdata.RT <- longdata %>% filter(name %in% colnames(vol)) %>% 
  group_by(name) %>%  mutate(n=n(), RT.sd=sd(RT)) %>% ungroup() %>% 
  mutate(name=fct_reorder(name, RT))

RT.tol <- 0.17  # 10 seconds before or after in quantitative params
ggplot(longdata.RT, aes(x=RT, y=name,color=RT.sd)) + geom_jitter(width=0, height=0.4, size=1) + 
  scale_color_viridis_c(option="magma") + geom_text(aes(x=4.5, label=n)) +
  stat_summary(fun="median", fun.max=~median(.x)+RT.tol, fun.min=~median(.x)-RT.tol, geom="pointrange", color="magenta", size=0.5, shape=15)

#TODO the following compounds have multiple, overlapping RTs, also merge (2E)-2,7-dimethylocta-2,6-dien-1-ol with b-myrcene
mess <- c("p-mentha-1,3,8-triene", "carveol", "cosmene", "4,7-Methano-1H-indene, 2,4,5,6,7,7a-hexahydro-", "[(E)-hex-3-enyl] acetate")
longdata.RT.mess <- longdata.RT %>% filter(name %in% mess) %>% 
  arrange(RT) %>% mutate(cluster = kmeans(RT, 4)$cluster) %>% 
  group_by(cluster) %>% mutate(RT.cluster = round(mean(RT),2))
ggplot(longdata.RT.mess, aes(x=factor(RT.cluster), fill=name)) + geom_bar()
ggplot(longdata.RT.mess, aes(x=RT, color=name, fill=name)) + facet_wrap(vars(RT.cluster), scales="free_x") + theme_minimal() +
  geom_density(alpha=0.2, linewidth=2) + geom_jitter(aes(y=-as.integer(factor(name))*10), width=0.0002, height=4) 
```


# Heatmap

```{r heatmap, dev='png', dev.args=list()}
library(pheatmap)
library(dendsort)
library(viridis)
ph  <- pheatmap(as.matrix(t(vol))^(1/4), 
         cluster_cols=T, show_colnames=F,
         clustering_method="mcquitty", clustering_distance_rows="correlation",
         clustering_distance_cols=vegdist(vol, method = "bray"),
         clustering_callback = function(hc, ...){dendsort(hc, type="average")},
         scale="none", color=magma(512),
         annotation_col = data.frame(meta %>% select("species","treatment","time"), row.names=rownames(vol)),
         annotation_row = data.frame(added = as.integer(colnames(vol) %in% added_quant), 
                                     new = as.integer(colnames(vol) %in% new_quant),
                                     need = as.integer(colnames(vol) %in% need_quant),
                                     row.names=colnames(vol)),
   fontsize = 10, border_color = NA, legend=F, annotation_legend=T, cutree_rows=6
)
```

# Ordination

```{r cap}
(cap_treat <- vegan::capscale(sqrt(vol) ~ species + time + treatment, data=meta))
anova.cca(cap_treat, by="margin") # samples should be averaged by plant first

plot(cap_treat, type="n")
points(cap_treat, display="sites", 
       pch=c(1,19)[as.integer(meta$time)],
       col=c("darkred","magenta")[as.integer(meta$species)])
legend("topleft", levels(meta$species), title="Species", fill=c("darkred","magenta"))
legend("topright", levels(meta$time), title="Time", pch=c(1,19))
text(cap_treat, display="species", cex=0.5, col=3)
text(cap_treat, display="cn", cex=0.5)
kable(arrange(as.data.frame(cap_treat$CCA$v), CAP1)) 
```
